### ISSUE TITLE
Should now be able to re-enable ppc64le for geospatial

### ISSUE THREAD

**Issue by xylar** [conda-forge/gz-common-feedstock#34]
`libgdal` has re-enabled ppc64le support in https://github.com/conda-forge/gdal-feedstock/pull/968.

Let me know if you all need help.  Otherwise, I'll leave it up to you since it's a tad more complicated than in other feedstocks.

**Comment by traversaro** [comment]
Thanks, I had missed this. We need to basically revert all the PRs that link back to https://github.com/conda-forge/gz-common-feedstock/pull/31 , I will use this issue to track this.

**Comment by Tobias-Fischer** [comment]
I think we can close here @traversaro

**Comment by traversaro** [comment]
Yes, fixed in https://github.com/conda-forge/gz-common-feedstock/pull/44 .
